### ISSUE TITLE
Why is this library copied into multiple projects, but never released separately?

### ISSUE THREAD

**Issue by pemensik** [farsightsec/libmy#5]
[Fedora Packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/#packaging-static-libraries) require separate packaging of libraries, when they can be packaged separately. Also shared libraries should be always used.

Is there any specific reason, why this library is shared by multiple projects, but they don't support building it in form of shared library? Why is only source files copying used?

**Comment by cmikk** [comment]
Despite its name starting with 'lib', `libmy` is not a standalone 
library or a coherent framework, but rather a grab bag of miscellaneous
generally unrelated utility functions, convenience wrappers, macros, and
data structures we've written and/or collected over the years. The
files contained in `libmy` would conventionally be in a `misc`, `util`,
`contrib`, or similar directory in many C projects, if not mingled
with the main sources. 

Because of this miscellaneous nature, and that projects typically
use only a handful of files from this collection with very little overlap
between projects, it makes little sense to merge this collection into a single
dependency.
